# Generated by Django 2.2.6 on 2021-12-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(blank=True, max_length=60)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('tin_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('gst_number', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(upload_to='customer')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('pin_code', models.CharField(blank=True, max_length=60)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='created date')),
                ('modified_at', models.DateTimeField(verbose_name='modified date')),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'accounts_customers',
            },
        ),
    ]
