# Generated by Django 2.2.6 on 2021-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211210_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=50),
            preserve_default=False,
        ),
    ]
