# Generated by Django 2.2.6 on 2021-12-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211211_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('unit_name', models.CharField(max_length=50, unique=True)),
                ('unit_type', models.CharField(max_length=50, unique=True)),
                ('unit_description', models.TextField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
            ],
            options={
                'verbose_name_plural': 'Unit of Measurement',
                'db_table': 'accounts_unit_of_measurement',
            },
        ),
    ]
