# Generated by Django 2.2.6 on 2021-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_unitofmeasurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_description', models.TextField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
            ],
            options={
                'verbose_name_plural': 'Product Category',
                'db_table': 'accounts_Category',
            },
        ),
    ]
