# Generated by Django 2.2.6 on 2021-12-12 11:40

import app.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.SlugField(null=True),
        ),
    ]
