# Generated by Django 2.2.6 on 2021-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211212_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='tag',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='tax',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
