# Generated by Django 2.2.6 on 2021-12-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211212_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='unitofmeasurement',
            name='status',
            field=models.BooleanField(default=False, max_length=50),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('expense_date', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, max_length=400, null=True)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
                ('expense_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MasterExpenses', to='accounts.MasterExpenses')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentTypes', to='accounts.PaymentTypes')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'db_table': 'accounts_expenses',
            },
        ),
    ]
