# Generated by Django 2.2.6 on 2021-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20211212_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
