# Generated by Django 2.2.6 on 2021-12-12 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20211212_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=55, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('email', models.CharField(blank=True, max_length=55, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=40, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=40, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('contact_name', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.IntegerField(blank=True, null=True)),
                ('contact_mobile', models.IntegerField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='company')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=60, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'accounts_company',
            },
        ),
        migrations.RemoveField(
            model_name='customeraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Accounts',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
