# Generated by Django 2.2.6 on 2021-12-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211212_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('credit_date', models.DateTimeField(verbose_name='credit date')),
                ('reference_number', models.TextField(blank=True, max_length=400, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
                ('company_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='accounts.Company')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentType', to='accounts.PaymentTypes')),
            ],
            options={
                'verbose_name_plural': 'Credit',
                'db_table': 'accounts_credit',
            },
        ),
    ]
