# Generated by Django 2.2.6 on 2021-12-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211212_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
