# Generated by Django 2.2.6 on 2021-12-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211212_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('BOTH', 'Both')], default='SELLER', max_length=6),
        ),
    ]
