# Generated by Django 2.2.6 on 2021-12-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20211212_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='company_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.Company'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt', to='accounts.PaymentTypes'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='reference_number',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=100, unique=True)),
                ('debit_date', models.DateTimeField(verbose_name='debit date')),
                ('reference_number', models.TextField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('status', models.BooleanField(default=False, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='modified date')),
                ('company_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='accounts.Company')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentType', to='accounts.PaymentTypes')),
            ],
            options={
                'verbose_name_plural': 'Debits',
                'db_table': 'accounts_debit',
            },
        ),
    ]
