# Generated by Django 2.2.6 on 2021-12-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20211212_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'verbose_name_plural': 'Credits'},
        ),
        migrations.AddField(
            model_name='products',
            name='min_stock',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='current_stock',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
