# Generated by Django 2.2.6 on 2021-12-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211213_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccounts',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
    ]
