# Generated by Django 2.2.6 on 2023-09-10 16:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_auto_20211224_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_item', to='accounts.Products'),
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=25, message='Name must be at least 25 characters long.')])),
                ('mobile1', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Mobile number must be exactly 10 digits.')])),
                ('mobile2', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Mobile number must be exactly 10 digits.')])),
                ('doorNumber', models.CharField(max_length=50)),
                ('nameOnNamePlate', models.CharField(max_length=255)),
                ('adharNumber', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='Adhar number must be 12 digits.')])),
                ('geoLocation', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizens_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
