# Generated by Django 2.2.6 on 2023-09-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStore', '0002_citizen_nooneathome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='adharNumber',
            new_name='AadhaarNumber',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='noOneAtHome',
            field=models.BooleanField(default=False, verbose_name='No One AtHome'),
        ),
    ]
