# Generated by Django 2.2.6 on 2023-09-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStore', '0003_auto_20230910_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='noOneAtHome',
            field=models.BooleanField(default=False, verbose_name='No one at home'),
        ),
    ]
