# Generated by Django 2.2.6 on 2023-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataStore', '0004_auto_20230910_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='mobile1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='mobile2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
