# Generated by Django 2.2.6 on 2023-09-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataStore', '0006_auto_20230910_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='_citizen_id',
            new_name='citizen_id',
        ),
    ]
